version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: gourmet_express_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: gourmet_express
      MYSQL_USER: gourmet_user
      MYSQL_PASSWORD: gourmet1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data: